format = """
[░▒▓](#0cff76)\
[](bg:#09b755 fg:#0cff76)\
$directory\
[](fg:#09b755 bg:#06674b)\
$git_branch\
$git_status\
[](fg:#06674b bg:#032333)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#032333 bg:#021627)\
$time\
[ ](fg:#021627)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#09b755"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#06674b"
format = '[[ $symbol $branch ](fg:#0cff76 bg:#06674b)]($style)'

[git_status]
style = "bg:#06674b"
format = '[[($all_status$ahead_behind )](fg:#0cff76 bg:#06674b)]($style)'

[nodejs]
symbol = ""
style = "bg:#06674b"
format = '[[ $symbol ($version) ](fg:#0cff76 bg:#06674b)]($style)'

[rust]
symbol = ""
style = "bg:#06674b"
format = '[[ $symbol ($version) ](fg:#0cff76 bg:#06674b)]($style)'

[golang]
symbol = ""
style = "bg:#06674b"
format = '[[ $symbol ($version) ](fg:#0cff76 bg:#06674b)]($style)'

[php]
symbol = ""
style = "bg:#06674b"
format = '[[ $symbol ($version) ](fg:#0cff76 bg:#06674b)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#021627"
format = '[[  $time ](fg:#e3e5e5 bg:#021627)]($style)'